import { CheckCircleIcon } from "@phosphor-icons/react/dist/ssr";
import { StaggerContainer } from "@/components/interfaces/motion/StaggerContainer";
import { StaggerItem } from "@/components/interfaces/motion/StaggerItem";
import { Badge } from "@/components/interfaces/ui/Badge";
import { Typography } from "@/components/interfaces/ui/Typography/Typography";
import { EXPERIENCE } from "@/lib/config/experience";
import { SECTION_IDS } from "@/lib/tools/types";

export function ExperienceTimeline() {
  return <section id={SECTION_IDS.experienceList} className="mx-auto min-h-screen w-full max-w-5xl scroll-mt-20 px-6 py-14 sm:py-20">
    <div className="max-w-2xl"><Typography as="p" variant="text" size="xs" className="tracking-[0.22em] text-coral">PROFESSIONAL CHAPTERS</Typography><Typography as="h1" variant="header" size="5xl" className="mt-3 leading-none sm:text-7xl">Experience built through ownership.</Typography><Typography variant="text" size="sm" className="mt-5 max-w-xl leading-7 text-text-on-dark/70">Roles, responsibilities, and evidence of impact across AI engineering, delivery, and frontend leadership.</Typography></div>
    <StaggerContainer trigger="mount" className="mt-14 space-y-5">{EXPERIENCE.map((experience, index) => <StaggerItem key={experience.organization}><article className="rounded-2xl border border-text-on-dark/15 bg-ink-panel/80 p-6 text-text-on-dark shadow-xl backdrop-blur-md sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="font-mono text-[11px] tracking-[0.2em] text-coral">CHAPTER 0{index + 1}</span><Typography as="h2" variant="header" size="2xl" className="mt-2">{experience.organization}</Typography></div><Typography as="span" variant="text" size="xs" className="font-mono opacity-55">{experience.location}</Typography></div><div className="mt-7 space-y-8">{experience.roles.map((role) => <section key={role.title} className="border-t border-text-on-dark/10 pt-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2"><Typography as="h3" variant="header" size="lg">{role.title}</Typography><CheckCircleIcon size={16} className="text-frame-green" aria-label="Verified from CV" /></div><Typography as="span" variant="text" size="xs" className="rounded-full bg-text-on-dark/10 px-3 py-1 font-mono">{role.period}</Typography></div><ul className="mt-4 grid gap-3 md:grid-cols-2">{role.contributions.map((contribution) => <li key={contribution} className="flex gap-3 font-sans text-sm leading-6 text-text-on-dark/75"><span aria-hidden="true" className="mt-2.5 size-1.5 shrink-0 rounded-full bg-mustard" />{contribution}</li>)}</ul><div className="mt-5 flex flex-wrap gap-2">{role.technologies.map((technology) => <Badge key={technology} color="slate">{technology}</Badge>)}</div></section>)}</div></article></StaggerItem>)}</StaggerContainer>
  </section>;
}
