import type { Metadata } from "next";
import { bigHeaderFont, headerFont, paragraphFont } from "@/components/ui/Typography/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bigHeaderFont.variable} ${headerFont.variable} ${paragraphFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
